### ISSUE TITLE
Set up & test amino types & signing

### ISSUE THREAD

**Issue by haveanicedavid** [regen-network/groups-ui#10]
Amino signing hasn't been tested, and there are likely issues with how it functions. Need to set up & test with ledger

**Comment by blushi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Regen-Registry-5f8998bec8958d000f4609e2/issues/regen-network/groups-ui/10?planning-poker) with Zenhub @haveanicedavid @ryanchristo

**Comment by ryanchristo** [comment]
Most of this work will need to happen in the regen-js repository. Telescope has an option for amino configuration. This issue is still relevant for groups-ui specifically but I'll open an issue in regen-js to configure amino types.

**Comment by ryanchristo** [comment]
Issue in regen-js created: https://github.com/regen-network/regen-js/issues/70

**Comment by ryanchristo** [comment]
Group amino types are already registered correctly. This is not dependent on the regen-js issue. Currently testing with a ledger device produces the following error:

![Screenshot from 2023-05-23 12-55-55](https://github.com/regen-network/groups-ui/assets/12519942/2eec8db8-2b0b-4261-90e7-f0342cc52e1c)

Updating `keplr.getOfflineSigner(chainId)` to `keplr.getOfflineSignerOnlyAmino(chainId)` produces the following error when using a ledger device:

![Screenshot from 2023-05-23 13-02-14](https://github.com/regen-network/groups-ui/assets/12519942/faa97293-ea3b-46df-ba95-46e4c3a22db0)

And with the update without using a ledger device:

![Screenshot from 2023-05-23 13-06-18](https://github.com/regen-network/groups-ui/assets/12519942/8de5e82e-221f-4904-88ff-5862a870c72a)

**Comment by ryanchristo** [comment]
Looks like the above may be due to the amino type for `ThresholdDecisionPolicy` specifically.

```
type: cosmos-sdk/MsgCreateGroupWithPolicy
value:
  admin: regen1jx34255cgvxpthkg572ma6rhq6crwl6x2s4ajx
  decision_policy:
    type_url: /cosmos.group.v1.ThresholdDecisionPolicy
    value:
      '0': 10
      '1': 1
      '2': 49
      '3': 18
      '4': 16
      '5': 10
      '6': 8
      '7': 8
      '8': 128
      '9': 163
      '10': 5
      '11': 16
      '12': 128
      '13': 163
      '14': 5
      '15': 18
      '16': 4
      '17': 8
      '18': 1
      '19': 16
      '20': 1
  group_metadata: >-
    {"name":"Foo Bar","description":"","forumLink":"","updatedAt":"Tue May 30
    2023 10:44:17 GMT-0700 (Pacific Daylight Time)","other":""}
  group_policy_as_admin: true
  group_policy_metadata: ''
  members:
    - address: regen1l2pwmzk96ftmmt5egpjulyqtneygmmzndf7csk
      metadata: ''
      weight: '1'
```

**Comment by ryanchristo** [comment]
Looks like this is a known issue and may have been resolved...

https://github.com/osmosis-labs/telescope/issues/281
