### ISSUE TITLE
Gracefully handle groups which weren't created through UI

### ISSUE THREAD

**Issue by haveanicedavid** [regen-network/groups-ui#11]
Much of the UI is contingent upon metadata which might not exist within on-chain groups (IE if they're created through CLI). 

These should be gracefully handled, maybe with some information 
- If there's no name, show `Group #[number]`
- If there's no description, just don't render

**Comment by blushi** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Regen-Registry-5f8998bec8958d000f4609e2/issues/regen-network/groups-ui/11?planning-poker) with Zenhub @haveanicedavid

**Comment by wgwz** [comment]
Is this a related part of the code @haveanicedavid ? I was just curious about this and started looking into it:
https://github.com/regen-network/groups-ui/blob/67d96baf32e814afab2e9a664d02fe03e30350ae/src/components/organisms/proposal-summary.tsx#L53-L54

**Comment by ryanchristo** [comment]
@wgwz are you still looking into this? If not, I'd be happy to pick it up.

> Is this a related part of the code @haveanicedavid ?

Yea, this is part of the solution. This is where we would need to render the alternative data if not available.

**Comment by wgwz** [comment]
@ryanchristo feel free! i was just researching and adding notes, no further work being done on my side
