### ISSUE TITLE
"Edit group" button displayed even when not group admin

### ISSUE THREAD

**Issue by blushi** [regen-network/groups-ui#122]
The "Edit group" button is displayed even if you're not an admin of the group, which would always result in a failed tx if the user tries it out. 
It should only be displayed if you're the admin or the admin is the group policy.

**Comment by ryanchristo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RND-Dev-Team-5f8998bec8958d000f4609e2/issues/regen-network/groups-ui/122?planning-poker) with Zenhub @blushi @wgwz
