### ISSUE TITLE
Add "Exec" button on the proposal page when applicable

### ISSUE THREAD

**Issue by blushi** [regen-network/groups-ui#130]
We could add an "Exec" button on the proposal page when applicable, currently it's only available from the proposals table on the groups page.

**Comment by ryanchristo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RND-Dev-Team-5f8998bec8958d000f4609e2/issues/regen-network/groups-ui/130?planning-poker) with Zenhub @blushi @ryanchristo @wgwz
