### ISSUE TITLE
Suggestion: Change usage of "Group Policy" to "Group Account"

### ISSUE THREAD

**Issue by clevinson** [regen-network/groups-ui#148]
I think it would be clearer and easier to understand the functionality of groups (and the distinction between groups and group policies) if we called the secondary entity of a group (for which we have a decision policy, an address, and an admin) the "Group Account" instead of a "Group Policy".

Calling this secondary entity "Group Account" seems appropriate to me because if the "Decision Policy" or "admin" are updated / changed, the "Group Account" still exists, holds the same amount of funds, and is represented by the same address.

Under the current naming (calling this entity the "Group Policy"), it falsely gives users the impression that the decision policy itself is the primary un-changeable component of the entity.  It also tends to confuse users when telling them that the "group policy" holds funds.  Saying that a "Group Account" holds funds, makes more sense imo.

My suggestion is for us to first have this discussion at the UI level, because most users won't need to engage with the CLI or with actual API calls.  If from a user-perspective, we do make this decision to change the naming from "Group Policy" to "Group Account", I would suggest we update all user-facing text & copy within the groups-ui repo to use this new name, and then independently file an issue in cosmos-sdk to suggest that this naming be updated in the API / on-chain groups functionality as well.  Though I imagine that conversation would take longer, and the resulting changes may not be updated for a while.

**Comment by ryanchristo** [comment]
duplicate #58

**Comment by clevinson** [comment]
After posting my initial description of this issue as a comment to #58, I think it makes sense to close this issue so we can continue the conversation in #58
