### ISSUE TITLE
Have two deployed versions of groups-ui

### ISSUE THREAD

**Issue by haveanicedavid** [regen-network/groups-ui#15]
Question: Is this about having a staging & production environment? Where each one can be configured to any number of chains (assuming we go with the multi-chain config strategy)?

**Comment by blushi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Regen-Registry-5f8998bec8958d000f4609e2/issues/regen-network/groups-ui/15?planning-poker) with Zenhub @haveanicedavid @ryanchristo

**Comment by clevinson** [comment]
Is this about having a staging & production environment?  Where each one can be configured to any number of chains (assuming we go with the multi-chain config strategy)?

**Comment by blushi** [comment]
> Is this about having a staging & production environment? 
I think this was the original idea, using redwood and mainnet respectively.
But if we go with the multi-chain config strategy, I'm wondering if instead we could just add available testnets as part of the selectable chains (just like in Keplr)

**Comment by clevinson** [comment]
We should probably re-look at this once the MVP tasks are closer to finished. 

Let's update this issue to be focused on:
- getting a deployed instance of Groups UI against mainnet (either w/ multi chain config, or separate instance)
- having a staging deployment that is distinct from production deployment (of front-end code)

**Comment by ryanchristo** [comment]
> Let's update this issue to be focused on:
>
> - getting a deployed instance of Groups UI against mainnet (either w/ multi chain config, or separate instance)
> - having a staging deployment that is distinct from production deployment (of front-end code)

New proposal following group working call:

- add regen mainnet to configuration
- add separate `production` branch
- set up `groups.regen.network` to deploy off `production`
- new `regen-groups.netlify` to deploy off `main` (i.e. staging)

**Comment by blushi** [comment]
@ryanchristo why not having a release flow similar to the one for web-registry https://www.notion.so/Release-process-for-regen-web-3dce8a42813b466fa46d44e8723a3b62? ie with a `dev` and `main` branch instead of `main` and `production` respectively as proposed above?

**Comment by ryanchristo** [comment]
Yea, that sounds good.
