### ISSUE TITLE
Groups App not Loading for Mainnet

### ISSUE THREAD

**Issue by S4mmyb** [regen-network/groups-ui#153]
The groups application does not work for mainnet. After ~30 seconds load time, a screen pops up telling me I need to enable Keplr to run the app. Clicking the button, however does nothing. 

If I switch to redwood the application loads fine. See image below. 

![image](https://github.com/regen-network/groups-ui/assets/67330492/51ddaf33-17ca-4f81-860f-8a6e9af364f7)

**Comment by ryanchristo** [comment]
RND full node was temporarily unavailable and is now back online.
