### ISSUE TITLE
Reading generic messages in proposals

### ISSUE THREAD

**Issue by haveanicedavid** [regen-network/groups-ui#16]
Currently the groups UI only renders proposal actions that we have explicitly implemented renderers for.  If a proposal exists where the `msgs` array has a msg that is unparseable / unrecognized by the groups-ui, we should have a fall-back display for how to present the msg.

Possibly this should be JSON, maybe some table rendering of keys & values? JSON is probably easiest.

Examples are how block explorers support parsable messages:
https://www.mintscan.io/regen/txs/7E2A85C217FB62B1E45941AECDE0CD48C60815F487FA2E5091457411F93293B2

And also fallback behavior for how to display custom msg's that are not recognized by the block explorer:
https://www.mintscan.io/regen/txs/8099F8AE8CF0B9A7EE0AAC5CD09E129D0707B3C2316DA7C166837E51266FEEA1

The msg being parsed here is:
```json
{
  "@type": "/regen.ecocredit.marketplace.v1.MsgBuyDirect",
  "buyer": "regen1l0ck43z80q7uzfd70qzsm9lggwvz3gdy774x30",
  "orders": [
    {
      "sell_order_id": "1",
      "quantity": "0.09",
      "bid_price": {
        "denom": "ibc/334740505537E9894A64E8561030695016481830D7B36E6A9B6D13C608B55653",
        "amount": "40000000"
      },
      "disable_auto_retire": true,
      "retirement_jurisdiction": ""
    }
  ]
}
```

Note: In Mintscan, they take a hybrid approach where the parse out the top level keys & values from the JSON object into a table format, and any values that are nested JSON objects are presented as JSON strings.

**Comment by blushi** [comment]
cc/ @clevinson

**Comment by erikalogie** [comment]
@haveanicedavid can you review this? I'm not sure if I captured exactly what you meant with this task description: https://www.figma.com/file/Mqvg4sP0Gwk1Jn4svsmhDp/Groups-UI?node-id=4808%3A24292&t=hTVHnRRuJHK94ws1-1

**Comment by haveanicedavid** [comment]
@erikalogie my task description wasn't very clear, but the mockup LGTM
