### ISSUE TITLE
Add support for currencies other than staking denom

### ISSUE THREAD

**Issue by haveanicedavid** [regen-network/groups-ui#19]
`regen`, `nct`, `usdc` tokens

**Comment by ryanchristo** [comment]
This is not part of the MVP at the moment but wondering if it should be? cc @haveanicedavid @clevinson @blushi

It makes sense for staking action but if a group wants to manage any other asset, they will be unable to send that asset from the group policy account using the ui. Happy to take a look at this this week if we think it should be part of the MVP.

Also related to some todos in the codebase regarding max amounts being dynamic:
https://github.com/regen-network/groups-ui/blob/f04e4ee0338ec2f88a56b8178ce0e8cfa5475adf/src/components/organisms/proposal-form.tsx#L133-L134
https://github.com/regen-network/groups-ui/blob/f04e4ee0338ec2f88a56b8178ce0e8cfa5475adf/src/components/organisms/proposal-form.tsx#L144-L145

**Comment by blushi** [comment]
I agree this should be part of the MVP.

**Comment by blushi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Regen-Registry-5f8998bec8958d000f4609e2/issues/regen-network/groups-ui/19?planning-poker) with Zenhub @haveanicedavid @ryanchristo
