### ISSUE TITLE
Clicking refresh gives a 404

### ISSUE THREAD

**Issue by clevinson** [regen-network/groups-ui#28]
On any page other than the homepage, clicking the refresh button results in a 404
<img width="646" alt="Screenshot 2023-04-12 at 4 14 37 PM" src="https://user-images.githubusercontent.com/832188/231611288-c14b324a-3bef-412d-8d55-6380f421c271.png">

Note: this might be related to something with our deploy setup / vite

**Comment by blushi** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Regen-Registry-5f8998bec8958d000f4609e2/issues/regen-network/groups-ui/28?planning-poker) with Zenhub @haveanicedavid

**Comment by blushi** [comment]
only happens on the netlify deploy, not locally
