### ISSUE TITLE
Insufficient funds when attempting to update a group

### ISSUE THREAD

**Issue by haveanicedavid** [regen-network/groups-ui#48]
Follow up from https://github.com/regen-network/groups-ui/pull/46#pullrequestreview-1394940040

> received an insufficient funds error when attempting to submit a transaction to update a group even though I have plenty of funds to do so. Only on updating an existing group and not an issue when creating a group.

Possibly related to a user's `admin` status within that group

**Comment by ryanchristo** [comment]
Taking a look at this now.

**Comment by ryanchristo** [comment]
Confirmed that this is only an issue when the policy is the admin.

**Comment by ryanchristo** [comment]
So this is actually related to adding group messages to proposals (#30).

**Comment by ryanchristo** [comment]
And we will need to figure out the workflow for updating a group (and policy) with the policy as the admin. When updating a group with policy as admin, the appropriate action is creating a proposal rather than attempting to execute the update as the user.

**Comment by ryanchristo** [comment]
The "redeploy" option should probably be "submit proposal" if the group policy is the admin. We may event want an additional step for reviewing the proposal / adding a title and description to the proposal depending on how we want to handle updating a group where group policy is the admin.

![Screenshot from 2023-04-24 09-44-15](https://user-images.githubusercontent.com/12519942/234062971-6cf38e3c-8988-4ff5-b14e-f98f7a8a41e1.png)

cc @clevinson @erikalogie

**Comment by ryanchristo** [comment]
Unassigned myself for now as this is dependent on knowing the UX flow for updating a group with policy as admin.

**Comment by erikalogie** [comment]
@ryanchristo I haven't reviewed this with @clevinson yet but this is kinda what I'm thinking thus far if helpful: https://www.figma.com/file/Mqvg4sP0Gwk1Jn4svsmhDp/Groups-UI?node-id=4800%3A24604&t=hTVHnRRuJHK94ws1-1

**Comment by blushi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Regen-Registry-5f8998bec8958d000f4609e2/issues/regen-network/groups-ui/48?planning-poker) with Zenhub @haveanicedavid @ryanchristo
