### ISSUE TITLE
Fix group policy toggle button 

### ISSUE THREAD

**Issue by haveanicedavid** [regen-network/groups-ui#5]
Currently, the group policy form isn’t configured as a toggle, and the UI is a bit confusing:

<img width="758" alt="CleanShot 2023-02-12 at 20 30 57@2x" src="https://user-images.githubusercontent.com/9052511/218364153-99f00fa8-d71d-4143-a5fb-66ed7c80017e.png">

How it should look: 
![CleanShot 2023-04-17 at 08.31.16@2x.png](https://images.zenhubusercontent.com/58d5565151aa2c3057796a58/31eed046-f27f-47db-8b86-413c5484e268)

See: https://www.figma.com/file/Mqvg4sP0Gwk1Jn4svsmhDp/Widgets?node-id=3443-48818&t=KQERsQNZuGGaZCgW-4

There was a toggle component created in the past in line with the mockups, but it seems like it got reverted… possibly in a git rebase. Might be worth checking through git history befroe building from scratch

**Comment by blushi** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Regen-Registry-5f8998bec8958d000f4609e2/issues/regen-network/groups-ui/5?planning-poker) with Zenhub @haveanicedavid
