### ISSUE TITLE
Internal Audit of Groups UI

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/groups-ui#62]
## Summary

We are currently working towards an MVP for the groups UI (https://github.com/regen-network/groups-ui/issues/29).

We should perform an internal audit of the codebase to identify issues that may need to be completed as part of the MVP (and is not already being tracked) as well as issues that we can resolve as part of future iterations.

***Note: At least two engineers should perform the audit.***

## Checklist

- [ ] Test application meets acceptance criteria defined within #29
- [ ] Review code architecture and identify any improvements that could be made
- [ ] Review designs and identify any interfaces that need to be implemented or updated
- [ ] Review dependencies and dependency versions and identify any updates that should be made
- [ ] Review the codebase and identify any todos that are not yet being tracked in issues

**Comment by blushi** [comment]
@ryanchristo probably best to make sure we have every MVP issues closed before looking it this?

**Comment by ryanchristo** [comment]
My notes from audit and testing:

- [ ] Test application meets acceptance criteria defined within #29
  - [x] Anyone can create a group with the group UI
    - as long as they have a keplr wallet, with or without a ledger device
  - [x]  Every group (whether created through UI or CLI) can be viewed by a member
    - all groups are visible to everyone, only groups that the user is a member of are displayed on the home page
  - [x]  If user is admin, they can manage group & group policies
    - the admin of a group can update the group metadata, create a group policy if no policy exists (a group was created using the CLI), and add and update members of a group
    - one thing that is not possible is updating the admin of a group, and therefore switching from a group admin to a policy admin, but this is now being tracked in #115
  - [x]  Text, Staking, Send, Group admin msgs, proposals can be made through the UI
    - group proposals with no messages, send messages, staking messages, and group admin messages can be submitted using the UI (not including the update admin message #115)
  - [x]  Every proposal type (made via UI or CLI) can be viewed, voted on, & executed
    - proposals submitted within and without the UI are viewable with messages being displayed as JSON in the event the UI does not support it, not a high-priority but noting we do have some unfinished work for displaying the new group update messages #111
    - proposals can be voted upon although a user should probably be able to update their vote as is possible with the group module event though prevented in the UI #120
    - proposals can be successfully executed although it would be nice to have some better error handling and prevention in the case the message will fail, which is something that has been discussed in #56
- [ ] Review code architecture and identify any improvements that could be made
  - ...
- [ ] Review designs and identify any interfaces that need to be implemented or updated
  - ...
- [ ] Review dependencies and dependency versions and identify any updates that should be made
  - ...
- [ ] Review the codebase and identify any todos that are not yet being tracked in issues
  - ...

Items required (from my perspective) before launching:
- [ ] finish wiring up historical proposals

Items that would be nice to have before or soon after launching:
- [ ] the ability to update group admin as a user admin
- [ ] the ability to update group admin via group proposal if policy admin
- [ ] historical proposals includes historical votes

**Comment by blushi** [comment]
My Audit (still WIP): https://hackmd.io/@3CueavWvQ0WoQqDc-lJ3gg/BJOIAtkj3

**Comment by wgwz** [comment]
As part of adding a graphql client, we have a small dependency which for some reason required being pinned 1 major version behind the latest. I don't think this is a major issue but a good thing to track for the future health of the groups-ui repo.

See this comment: https://github.com/regen-network/groups-ui/pull/112#discussion_r1276408464

Basically, with the combination of `react-query` + `graphql-request`, react-query asks us to use `graphql-request` v5x rather than v6x.

I think a good task for that at this stage could be simply to open an issue with `react-query` to specify what the plans are for supporting `graphql-request` v6x (investigate upgrade process for `graphql-request`).

**Comment by ryanchristo** [comment]
Opened #123 for tracking the graphql request version issue.

**Comment by blushi** [comment]
Should we close this now or is there something remaining?

**Comment by ryanchristo** [comment]
Completed. Thanks!
