### ISSUE TITLE
Add support for viewing historical proposals

### ISSUE THREAD

**Issue by clevinson** [regen-network/groups-ui#63]
Proposals that are pruned from the blockchain application state should be viewable within the groups ui using the indexer we currently have set up to index proposals.

**Comment by clevinson** [comment]
Dependent on:
- cosmos/cosmos-sdk#15938
- Possibly also: regen-network/analytics#6

**Comment by ryanchristo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Regen-Registry-5f8998bec8958d000f4609e2/issues/regen-network/groups-ui/63?planning-poker) with Zenhub @blushi @wgwz

**Comment by blushi** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Regen-Registry-5f8998bec8958d000f4609e2/issues/regen-network/groups-ui/63?planning-poker) with Zenhub @ryanchristo

**Comment by blushi** [comment]
@ryanchristo we're gonna need to set up the apollo client for querying the historical proposals, then merge those with the queryable proposals + test everything, do you think 3 works as an estimate for this then?
