### ISSUE TITLE
Fix proposal ID not found error

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/groups-ui#75]
Despite the proposal being successfully submitted, submitting a proposal results in the following error without redirecting the user to the group page to view the successfully submitted proposal:

![image](https://github.com/regen-network/groups-ui/assets/12519942/6504de6b-57ce-4a4b-9740-b3e75b236541)

**Comment by blushi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Regen-Registry-5f8998bec8958d000f4609e2/issues/regen-network/groups-ui/75?planning-poker) with Zenhub @haveanicedavid @ryanchristo
