### ISSUE TITLE
Fix stake proposal submission

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/groups-ui#77]
At the moment, only stake proposal type `delegate` can be submitted. A proposal with any other stake proposal type (`delegate`, `redelegate`, or `claim`) cannot be submitted. Attempting to click "Save & Next" does nothing.

**Comment by blushi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Regen-Registry-5f8998bec8958d000f4609e2/issues/regen-network/groups-ui/77?planning-poker) with Zenhub @haveanicedavid @ryanchristo
