### ISSUE TITLE
Implement claim staking rewards message

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/groups-ui#79]
In the current implementation, the staking proposal action includes "claim rewards". This message is not yet implemented.

```
  if (isClaimValues(values)) {
    console.warn('Not yet implemented! Cannot create claim message')
    // TODO: stakingClaimMsg currently only accepts arguments for delegator &
    // validator addresses - from UX standpoint though we should probably target
    // something like Keplr where it's just a simple "claim"
    // return stakingClaimMsg({})
  }
```

**Comment by blushi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Regen-Registry-5f8998bec8958d000f4609e2/issues/regen-network/groups-ui/79?planning-poker) with Zenhub @haveanicedavid @ryanchristo
