### ISSUE TITLE
Fix empty messages in fetched proposal

### ISSUE THREAD

**Issue by haveanicedavid** [regen-network/groups-ui#9]
There's currently a bug where messages aren't properly being added to a proposal - they show, but are empty so when an admin goes to execute, things don't behave as expected. Need to make sure all relevant messages are added to a proposal to fix execution

---

**UPDATE** - @ryanchristo

The message is included in the proposal on chain but fetching the proposal returns empty messages. The proposal messages were not being parsed correctly:

```
messages: [{typeUrl: undefined, value: undefined}]
```
 
This is due to an upstream issue in telescope (https://github.com/osmosis-labs/telescope/issues/321) but a workaround was added in https://github.com/regen-network/groups-ui/pull/59. This is now dependent upon https://github.com/regen-network/regen-js/issues/71, which is dependent upon https://github.com/osmosis-labs/telescope/issues/321.

**Comment by haveanicedavid** [comment]
Possibly being caused by #8

**Comment by blushi** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Regen-Registry-5f8998bec8958d000f4609e2/issues/regen-network/groups-ui/9?planning-poker) with Zenhub @haveanicedavid

**Comment by ryanchristo** [comment]
Investigating alongside #33. When fetching proposals, proposal messages are not returned with expected type `SDKAnyType` but rather each individual message type. We implement a workaround but would be ideal to resolve in the regen-ts library.

**Comment by ryanchristo** [comment]
Following up on my initial investigation. The fix would actually happen within telescope and is related to the following issue:

- https://github.com/osmosis-labs/telescope/issues/321

**Comment by ryanchristo** [comment]
I can implement a workaround for the time being but we should keep this issue open until the upstream issue is resolved.

**Comment by ryanchristo** [comment]
Upstream issue: https://github.com/regen-network/regen-js/issues/71
