### ISSUE TITLE
Proposal page for "Accepted" proposals has misleading information

### ISSUE THREAD

**Issue by clevinson** [regen-network/groups-ui#92]
If a proposal has status "ACCEPTED", it shows up in the "Ready to Execute" category on the group UI page (correct behavior).

However, when clicking into the proposal page itself, the vote buttons still display on the right-hand side, even though a user cannot vote on the proposal anymore.
<img width="1275" alt="Screenshot 2023-06-12 at 4 50 48 PM" src="https://github.com/regen-network/groups-ui/assets/832188/4a61ac82-c708-4b02-a543-6c6170e39169">

Clicking on one of these vote options results in sending an actual vote on-chain via Keplr, and the tx response is a failure with `failed to execute message; message index: 0: proposal not open for voting: invalid value` error message.

Additionally, the "Votes" box at the bottom displays "No Votes". This is technically accurate, as the proposal's individual votes have been pruned from state when the tally is finalized.  However, we should probably have a more clear way of communicating this in the UI (either by not rendering this section at all, or displaying the finalized tally of votes instead of individual votes of members).

**Comment by ryanchristo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RND-Dev-Team-5f8998bec8958d000f4609e2/issues/regen-network/groups-ui/92?planning-poker) with Zenhub @blushi @wgwz

**Comment by blushi** [comment]
> Additionally, the "Votes" box at the bottom displays "No Votes". This is technically accurate, as the proposal's individual votes have been pruned from state when the tally is finalized. However, we should probably have a more clear way of communicating this in the UI (either by not rendering this section at all, or displaying the finalized tally of votes instead of individual votes of members).

This last part should be addressed as part of #63 since we get the final tally result from the indexed proposal.

**Comment by ryanchristo** [comment]
Fixed by #113 and will be addressed in #63 (see https://github.com/regen-network/groups-ui/issues/92#issuecomment-1649765479).
