### ISSUE TITLE
Proposal state says "UNFINALIZED" even after proposal is accepted

### ISSUE THREAD

**Issue by clevinson** [regen-network/groups-ui#93]
If a proposal is "Accepted" or "Rejected", then it should be considered finalized.  Currently the code only checks for voting period having ended to see if the proposal is finalized or not.
<img width="897" alt="Screenshot 2023-06-12 at 4 57 00 PM" src="https://github.com/regen-network/groups-ui/assets/832188/6dfd2cfa-52a1-457d-a440-3001fb5eff2a">

**Comment by ryanchristo** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RND-Dev-Team-5f8998bec8958d000f4609e2/issues/regen-network/groups-ui/93?planning-poker) with Zenhub @blushi
